# Generated by Django 2.1 on 2018-10-20 14:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aula', models.CharField(choices=[('Palestra', 'Palestra'), ('Aula Normale', 'Aula Normale'), ('Aula Magna', 'Aula Magna'), ('Laboratorio di informatica', 'Laboratorio di informatica')], max_length=100)),
                ('capacita', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(max_length=1500)),
                ('is_progressive', models.BooleanField(default=True)),
                ('convalidato', models.BooleanField(default=False)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aula', to='app.Aula')),
            ],
        ),
        migrations.CreateModel(
            name='Fascia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fascia', models.CharField(choices=[('Prima Fascia', 'Prima Fascia'), ('Seconda Fascia', 'Seconda Fascia'), ('Terza Fascia', 'Terza Fascia')], default='Prima Fascia', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Giorno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno_della_settimana', models.CharField(choices=[('Lunedì', 'Lunedì'), ('Martedì', 'Martedì'), ('Mercoledì', 'Mercoledì'), ('Giovedì', 'Giovedì'), ('Venerdì', 'Venerdì')], default='Lunedì', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('classe', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('sezione', models.CharField(max_length=1)),
                ('hosted_courses', models.ManyToManyField(to='app.Corso')),
                ('iscrizioni', models.ManyToManyField(related_name='iscrizioni', to='app.Corso')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='utente',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fascia',
            name='giorno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Giorno'),
        ),
        migrations.AddField(
            model_name='corso',
            name='creatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatore', to='app.Utente'),
        ),
        migrations.AddField(
            model_name='corso',
            name='fasce',
            field=models.ManyToManyField(to='app.Fascia'),
        ),
        migrations.AddField(
            model_name='corso',
            name='iscritti',
            field=models.ManyToManyField(related_name='iscritti', to='app.Utente'),
        ),
        migrations.AddField(
            model_name='corso',
            name='ospitanti',
            field=models.ManyToManyField(to='app.Utente'),
        ),
    ]
