# Generated by Django 2.1 on 2018-10-20 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181020_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approva', models.BooleanField(default=False)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Corso')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Utente')),
            ],
        ),
    ]
