# Generated by Django 2.1 on 2018-10-17 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181017_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='hosted_course_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_course_2', to='app.Corso'),
        ),
    ]
