# Generated by Django 2.1 on 2018-10-18 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_utente_hosted_course_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='corso',
            name='creatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatore', to='app.Utente'),
        ),
        migrations.RemoveField(
            model_name='corso',
            name='ospitanti',
        ),
        migrations.AddField(
            model_name='corso',
            name='ospitanti',
            field=models.ManyToManyField(to='app.Utente'),
        ),
    ]
