# Generated by Django 2.1 on 2018-10-18 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181018_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fascia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fascia', models.CharField(choices=[('Prima Fascia', 'Prima Fascia'), ('Seconda Fascia', 'Seconda Fascia'), ('Terza Fascia', 'Terza Fascia')], default='Prima Fascia', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Giorno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno_della_settimana', models.CharField(choices=[('Lunedì', 'Lunedì'), ('Martedì', 'Martedì'), ('Mercoledì', 'Mercoledì'), ('Giovedì', 'Giovedì'), ('Venerdì', 'Venerdì')], default='Lunedì', max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='corso',
            name='fasce',
        ),
        migrations.AddField(
            model_name='fascia',
            name='giorno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Giorno'),
        ),
        migrations.AddField(
            model_name='corso',
            name='fasce',
            field=models.ManyToManyField(to='app.Fascia'),
        ),
    ]
