# Generated by Django 2.1 on 2018-10-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_permessi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permessi',
            name='corso',
        ),
        migrations.RemoveField(
            model_name='permessi',
            name='utente',
        ),
        migrations.DeleteModel(
            name='Permessi',
        ),
    ]
