# Generated by Django 2.1 on 2018-10-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181018_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utente',
            name='hosted_course_2',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='hosted_courses',
        ),
        migrations.AddField(
            model_name='utente',
            name='hosted_courses',
            field=models.ManyToManyField(to='app.Corso'),
        ),
    ]
