# Generated by Django 2.1 on 2018-10-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181025_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='corso',
            name='full',
            field=models.BooleanField(default=False),
        ),
    ]
