# Generated by Django 2.1 on 2018-10-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181018_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='corso',
            name='iscritti',
            field=models.ManyToManyField(related_name='iscritti', to='app.Utente'),
        ),
    ]
