# Generated by Django 2.1 on 2018-10-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_corso_iscritti'),
    ]

    operations = [
        migrations.AddField(
            model_name='corso',
            name='descrizione',
            field=models.CharField(default='descizione test', max_length=1000),
            preserve_default=False,
        ),
    ]
