# Generated by Django 2.1 on 2018-10-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_corso_descrizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='descrizione',
            field=models.TextField(max_length=1500),
        ),
    ]
